EXAMPLE_SELECTOR:
  NAME: studentid_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: o3-mini-2025-01-31
  TEMPERATURE: 2.0
PROMPT:
  NAME: replicate_student_tomato_studentlevel
STRUCTURED_OUTPUTTER:
  NAME: student
STUDENT_SCALE:
  NAME: proficiency_5_str
