EXAMPLE_SELECTOR:
  NAME: studentid_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: claude-3-5-haiku-20241022
  TEMPERATURE: 1.0
PROMPT:
  NAME: replicate_student_tomato_studentlevel
STRUCTURED_OUTPUTTER:
  NAME: student
