EXAMPLE_SELECTOR:
  NAME: studentid_semantic
  NUM_EXAMPLES: 5
MODEL:
  NAME: gemini-2.5-flash-preview-05-20
  TEMPERATURE: 1.0
PROMPT:
  NAME: replicate_student_tomato
STRUCTURED_OUTPUTTER:
  NAME: student
