EXAMPLE_SELECTOR:
  NAME: studentid_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: o3-2025-04-16
  TEMPERATURE: 0.0
PROMPT:
  NAME: replicate_student_tomato_studentlevel
STRUCTURED_OUTPUTTER:
  NAME: student
