EXAMPLE_SELECTOR:
  NAME: studentid_semantic
  NUM_EXAMPLES: 5
MODEL:
  NAME: claude-sonnet-4-20250514
  TEMPERATURE: 2.0
PROMPT:
  NAME: replicate_student_tomato_studentlevel
STRUCTURED_OUTPUTTER:
  NAME: student
STUDENT_SCALE:
  NAME: proficiency_5_str
