EXAMPLE_SELECTOR:
  NAME: studentid_semantic
  NUM_EXAMPLES: 5
MODEL:
  NAME: gemini-2.5-flash-preview-05-20
  TEMPERATURE: 2.0
PROMPT:
  NAME: replicate_teacher_onion_studentlevel
ROLEPLAY:
  STUDENT_SCALE: proficiency_5_str
STRUCTURED_OUTPUTTER:
  NAME: teacher
