EXAMPLE_SELECTOR:
  NAME: studentid_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: gemini-2.5-pro-preview-06-05
  TEMPERATURE: 1.0
PROMPT:
  NAME: replicate_teacher_avocado
STRUCTURED_OUTPUTTER:
  NAME: teacher
