EXAMPLE_SELECTOR:
  NAME: studentid_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: o3-2025-04-16
  TEMPERATURE: 2.0
PROMPT:
  NAME: replicate_teacher_onion_studentlevel
STRUCTURED_OUTPUTTER:
  NAME: teacher
STUDENT_SCALE:
  NAME: proficiency_5_str
