EXAMPLE_SELECTOR:
  NAME: studentid_semantic
  NUM_EXAMPLES: 5
MODEL:
  NAME: claude-3-5-haiku-20241022
  TEMPERATURE: 2.0
PROMPT:
  NAME: replicate_teacher_onion_studentlevel
STRUCTURED_OUTPUTTER:
  NAME: teacher
STUDENT_SCALE:
  NAME: proficiency_5_str
