EXAMPLE_SELECTOR:
  NAME: studentid_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: claude-sonnet-4-20250514
  TEMPERATURE: 2.0
PROMPT:
  NAME: replicate_teacher_avocado
STRUCTURED_OUTPUTTER:
  NAME: teacher
