MODEL:
  NAME: [
    "gemma3:12b", 
    # "qwen3:8b",
    ]
  TEMPERATURE: [0.0, 1.0]

STRUCTURED_OUTPUTTER:
  NAME: "teacher"

PROMPT:
  NAME: [
    "replicate_teacher_onion",
    "replicate_teacher_avocado"
  ]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [3, 5]
  NAME: ["studentid_random", "studentid_kc_exact", "studentid_semantic"]

