MODEL:
  NAME: ["gemini-2.5-flash-preview-05-20",
         "gemini-2.5-pro-preview-06-05",
         "claude-sonnet-4-20250514",
         "claude-3-5-haiku-20241022",
         "o3-2025-04-16",
         "o3-mini-2025-01-31",
         "o4-mini-2025-04-16",
  ]
  TEMPERATURE: [2.0]

STRUCTURED_OUTPUTTER:
  NAME: "student"

PROMPT:
  NAME: ["replicate_student_tomato_studentlevel"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [5]
  NAME: ["studentid_random", "studentid_semantic"]

ROLEPLAY:
  STUDENT_SCALE: ["proficiency_5_str"]