MODEL:
  NAME: [
         "gemini-2.5-flash-preview-05-20",
         "gemini-2.5-pro-preview-06-05",
         "claude-sonnet-4-20250514",
         "claude-3-5-haiku-20241022",
  ]
  TEMPERATURE: [1.0]

STRUCTURED_OUTPUTTER:
  NAME: "teacher"

PROMPT:
  NAME: ["replicate_teacher_onion_studentlevel"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [5]
  NAME: ["studentid_random", "studentid_semantic"]
  