CONTEXT_TYPE: snippets_misconceptions
EXAMPLE_FORMATTER:
  INTERACTIONS:
    NAME: quotes
  QUESTIONS:
    NAME: quotes
EXAMPLE_SELECTOR:
  EMBEDDING: text-embedding-3-large
  NAME: both_cfe_studentid_random
  NUM_EXAMPLES: 0
LOADER:
  DIFFICULTY_RANGE:
  - -5
  - 5
  JOIN_KEY: question_id
  NAME: dbe_kt22
MODEL:
  MAX_RETRIES: null
  MAX_TOKENS: 1024
  NAME: qwen3:1.7b
  TEMPERATURE: 0.0
  TIMEOUT: null
PROMPT:
  NAME: teacher_dbe_miscons_level_nocontext
ROLEPLAY:
  NUM_STUDENT_LEVELS: 5
  STUDENT_SCALE: proficiency_5_str
RUNS: 3
SEED: 42
STRUCTURED_OUTPUTTER:
  NAME: teacher_bool_nocontext
