EXAMPLE_SELECTOR:
  NAME: studentid_semantic
  NUM_EXAMPLES: 3
MODEL:
  NAME: claude-sonnet-4-20250514
  TEMPERATURE: 1.0
PROMPT:
  NAME: replicate_student_pepper
STRUCTURED_OUTPUTTER:
  NAME: student
