EXAMPLE_SELECTOR:
  NAME: studentid_kc_exact
  NUM_EXAMPLES: 5
MODEL:
  NAME: claude-sonnet-4-20250514
  TEMPERATURE: 1.0
PROMPT:
  NAME: replicate_student_pepper
STRUCTURED_OUTPUTTER:
  NAME: student
