MODEL:
  TEMPERATURE: [0.0, 1.0]

STRUCTURED_OUTPUTTER:
  NAME: "student_bool"

PROMPT:
  NAME: ["student_chocolate_level_context", "student_chocolate_nolevel_context"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [1, 3, 5, 10]
  NAME: ["studentid_random", "studentid_kc_exact"]
