MODEL:
  TEMPERATURE: [0.0, 1.0]

STRUCTURED_OUTPUTTER:
  NAME: "student"

PROMPT:
  NAME: ["replicate_miscon_student_chocolate"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [1, 3, 5, 10]
  NAME: ["miscon_studentid_random", "miscon_studentid_kc_exact"]
