EXAMPLE_SELECTOR:
  NAME: miscon_studentid_random
  NUM_EXAMPLES: 3
MODEL:
  NAME: qwen3:4b
  TEMPERATURE: 1.0
PROMPT:
  NAME: student_chocolate_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_kt
