EXAMPLE_SELECTOR:
  NAME: miscon_studentid_random
  NUM_EXAMPLES: 3
MODEL:
  NAME: llama3.2:3b
  TEMPERATURE: 0.0
PROMPT:
  NAME: teacher_marshmellow_level_context
STRUCTURED_OUTPUTTER:
  NAME: teacher_kt
