EXAMPLE_SELECTOR:
  NAME: miscon_studentid_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: llama3.1:8b
  TEMPERATURE: 1.0
PROMPT:
  NAME: teacher_marshmellow_level_context
STRUCTURED_OUTPUTTER:
  NAME: teacher_kt
