EXAMPLE_SELECTOR:
  NAME: miscon_studentid_kc_exact
  NUM_EXAMPLES: 1
MODEL:
  NAME: qwen3:1.7b
  TEMPERATURE: 1.0
PROMPT:
  NAME: teacher_marshmellow_level_context
STRUCTURED_OUTPUTTER:
  NAME: teacher_kt
