CONTEXT_TYPE: snippets_misconceptions
EXAMPLE_FORMATTER:
  INTERACTIONS:
    NAME: open_reading
  QUESTIONS:
    NAME: mcq_reading_quotes
EXAMPLE_SELECTOR:
  EMBEDDING: text-embedding-3-large
  NAME: both_cfe_studentlevel_random
  NUM_EXAMPLES: 1
LOADER:
  DIFFICULTY_RANGE:
  - 30
  - 110
  JOIN_KEY: null
  NAME: cupacfe
MODEL:
  MAX_RETRIES: null
  MAX_TOKENS: 1024
  NAME: qwen3:8b
  TEMPERATURE: 1.0
  TIMEOUT: null
PROMPT:
  NAME: teacher_cfe_miscons_level_context
ROLEPLAY:
  NUM_STUDENT_LEVELS: 5
  STUDENT_SCALE: proficiency_5_str
RUNS: 3
SEED: 42
STRUCTURED_OUTPUTTER:
  NAME: teacher_bool_nocontext
