EXAMPLE_SELECTOR:
  NAME: both_dbe_studentlevel_random
  NUM_EXAMPLES: 1
MODEL:
  NAME: qwen3:1.7b
  TEMPERATURE: 1.0
PROMPT:
  NAME: student_dbe_miscons_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_kt
