EXAMPLE_SELECTOR:
  NAME: both_dbe_studentlevel_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: llama3.2:1b
  TEMPERATURE: 0.0
PROMPT:
  NAME: teacher_dbe_miscons_level_context
STRUCTURED_OUTPUTTER:
  NAME: teacher_kt
