MODEL:
  TEMPERATURE: [0.0, 1.0]

STRUCTURED_OUTPUTTER:
  NAME: "teacher_bool"

PROMPT:
  NAME: ["teacher_marshmellow_level_context"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [1, 3, 5, 10]
  NAME: ["miscon_studentlevel_random", "miscon_studentlevel_kc_exact"]
