EXAMPLE_SELECTOR:
  NAME: miscon_studentid_kc_exact
  NUM_EXAMPLES: 5
MODEL:
  NAME: qwen3:1.7b
  TEMPERATURE: 0.0
PROMPT:
  NAME: student_chocolate_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool
