EXAMPLE_SELECTOR:
  NAME: miscon_studentid_random
  NUM_EXAMPLES: 1
MODEL:
  NAME: o4-mini-2025-04-16
  TEMPERATURE: 1.0
PROMPT:
  NAME: student_chocolate_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool
