EXAMPLE_SELECTOR:
  NAME: miscon_studentid_kc_exact
  NUM_EXAMPLES: 3
MODEL:
  NAME: llama3.1:8b
  TEMPERATURE: 1.0
PROMPT:
  NAME: student_chocolate_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool
