EXAMPLE_SELECTOR:
  NAME: miscon_studentid_kc_exact
  NUM_EXAMPLES: 5
MODEL:
  NAME: o4-mini-2025-04-16
  TEMPERATURE: 1.0
PROMPT:
  NAME: teacher_marshmellow_level_context
STRUCTURED_OUTPUTTER:
  NAME: teacher_bool
