EXAMPLE_SELECTOR:
  NAME: both_dbe_studentlevel_random
  NUM_EXAMPLES: 5
MODEL:
  NAME: qwen3:8b
  TEMPERATURE: 0.0
PROMPT:
  NAME: student_dbe_miscons_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool_nocontext
