EXAMPLE_SELECTOR:
  NAME: both_dbe_studentlevel_kc_exact
  NUM_EXAMPLES: 3
MODEL:
  NAME: qwen3:1.7b
  TEMPERATURE: 1.0
PROMPT:
  NAME: student_dbe_miscons_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool_nocontext
