EXAMPLE_SELECTOR:
  NAME: both_dbe_studentlevel_random
  NUM_EXAMPLES: 3
MODEL:
  NAME: qwen3:14b
  TEMPERATURE: 0.0
PROMPT:
  NAME: student_dbe_miscons_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool_nocontext
