MODEL:
  NAME: ["claude-sonnet-4-20250514",
  ]
  TEMPERATURE: [0.0, 1.0]

STRUCTURED_OUTPUTTER:
  NAME: "student"

PROMPT:
  NAME: ["replicate_student_pepper"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [3, 5]
  NAME: ["studentid_random", "studentid_kc_exact", "studentid_semantic"]