CONTEXT_TYPE: misconceptions
EXAMPLE_FORMATTER:
  INTERACTIONS:
    NAME: quotes
EXAMPLE_SELECTOR:
  EMBEDDING: text-embedding-3-large
  NAME: miscon_studentid_random
  NUM_EXAMPLES: 0
LOADER:
  JOIN_KEY: question_id
  NAME: dbe_kt22
MODEL:
  MAX_RETRIES: null
  MAX_TOKENS: 4096
  NAME: llama3.2:3b
  TEMPERATURE: 0.0
  TIMEOUT: null
PROMPT:
  NAME: teacher_marshmellow_level_nocontext
ROLEPLAY:
  NUM_STUDENT_LEVELS: 5
  STUDENT_SCALE: proficiency_5_str
RUNS: 3
SEED: 42
STRUCTURED_OUTPUTTER:
  NAME: teacher_kt
