
MODEL:
  NAME: ["gpt-4o-mini", "gpt-4o", "o3-mini"]
  TEMPERATURE: [0.0, 1.3, 2.0]

EXAMPLE_SELECTOR:
  NAME: ["random", "studentid_random", "studentid_semantic", "studentid_recency"]
  NUM_EXAMPLES: [1, 3, 5]
  EMBEDDING: ["text-embedding-3-large"]

PROMPT:
  NAME: ["student_A"]