MODEL:
  NAME: ["gemma3:12b", "qwen3:8b"]
  TEMPERATURE: [1.0]

STRUCTURED_OUTPUTTER:
  NAME: "student"

PROMPT:
  NAME: ["replicate_student_tomato"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [5]
  NAME: ["studentid_random", "studentid_semantic"]