MODEL:
  NAME: ["gemma3:12b", "qwen3:8b"]
  TEMPERATURE: [1.0]

STRUCTURED_OUTPUTTER:
  NAME: "teacher"

PROMPT:
  NAME: ["replicate_teacher_onion_studentlevel"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [5]
  NAME: ["studentid_random", "studentid_semantic"]
