# EXAMPLE_SELECTOR:
#   NUM_EXAMPLES: 0

PROMPT:
  # NAME: "teacher_cfe_miscons_level_nocontext"
  # NAME: "student_cfe_miscons_level_nocontext"
  NAME: "student_cfe_miscons_level_context"


STRUCTURED_OUTPUTTER:
  NAME: "student_bool_nocontext"
  # NAME: "teacher_bool_nocontext"