EXAMPLE_SELECTOR:
  NAME: studentid_kc_exact
  NUM_EXAMPLES: 5
MODEL:
  NAME: gemma3:12b
  TEMPERATURE: 1.0
PROMPT:
  NAME: replicate_student_tomato_studentlevel
STRUCTURED_OUTPUTTER:
  NAME: student
