EXAMPLE_SELECTOR:
  NAME: studentid_semantic
  NUM_EXAMPLES: 5
MODEL:
  NAME: gemma3:12b
  TEMPERATURE: 1.0
PROMPT:
  NAME: replicate_student_tomato_studentlevel
ROLEPLAY:
  STUDENT_SCALE: proficiency_5_str
STRUCTURED_OUTPUTTER:
  NAME: student
