EXAMPLE_SELECTOR:
  NAME: studentid_semantic
  NUM_EXAMPLES: 5
MODEL:
  NAME: qwen3:8b
  TEMPERATURE: 2.0
PROMPT:
  NAME: replicate_student_tomato_studentlevel
ROLEPLAY:
  STUDENT_SCALE: proficiency_5_str
STRUCTURED_OUTPUTTER:
  NAME: student
