MODEL:
  NAME: ["gemini-2.5-flash-preview-05-20",
         "gemini-2.5-pro-preview-06-05",
  ]
  TEMPERATURE: [0.0, 1.0]

STRUCTURED_OUTPUTTER:
  NAME: "student"

PROMPT:
  NAME: ["replicate_student_tomato"]

EXAMPLE_SELECTOR:
  NUM_EXAMPLES: [5]
  NAME: ["studentid_random"]