EXAMPLE_SELECTOR:
  NAME: miscon_studentid_random
  NUM_EXAMPLES: 1
MODEL:
  NAME: llama3.1:8b
  TEMPERATURE: 0.0
PROMPT:
  NAME: student_chocolate_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool
