CONTEXT_TYPE: errors
EXAMPLE_SELECTOR:
  NUM_EXAMPLES: 0
MODEL:
  NAME: llama3.1:8b
  TEMPERATURE: 1.0
PROMPT:
  NAME: teacher_cfe_errors_level_nocontext
STRUCTURED_OUTPUTTER:
  NAME: teacher_bool_nocontext
