CONTEXT_TYPE: errors
EXAMPLE_SELECTOR:
  NUM_EXAMPLES: 0
MODEL:
  NAME: qwen3:14b
  TEMPERATURE: 0.0
PROMPT:
  NAME: teacher_cfe_errors_level_nocontext
STRUCTURED_OUTPUTTER:
  NAME: teacher_bool_nocontext
