CONTEXT_TYPE: errors
EXAMPLE_SELECTOR:
  NAME: errors_studentlevel_random
  NUM_EXAMPLES: 1
MODEL:
  NAME: llama3.1:8b
  TEMPERATURE: 0.0
PROMPT:
  NAME: teacher_cfe_errors_level_context
STRUCTURED_OUTPUTTER:
  NAME: teacher_bool_nocontext
