CONTEXT_TYPE: errors
EXAMPLE_SELECTOR:
  NUM_EXAMPLES: 0
MODEL:
  NAME: qwen3:4b
  TEMPERATURE: 0.0
PROMPT:
  NAME: student_cfe_errors_level_nocontext
STRUCTURED_OUTPUTTER:
  NAME: student_bool_nocontext
