CONTEXT_TYPE: errors
EXAMPLE_SELECTOR:
  NAME: errors_studentlevel_random
  NUM_EXAMPLES: 1
MODEL:
  NAME: qwen3:1.7b
  TEMPERATURE: 0.0
PROMPT:
  NAME: student_cfe_errors_level_context
STRUCTURED_OUTPUTTER:
  NAME: student_bool_nocontext
