CONTEXT_TYPE: snippets
EXAMPLE_SELECTOR:
  NUM_EXAMPLES: 0
MODEL:
  NAME: llama3.2:3b
  TEMPERATURE: 0.0
PROMPT:
  NAME: student_cfe_snippet_level_nocontext
STRUCTURED_OUTPUTTER:
  NAME: student_bool_nocontext
