CONTEXT_TYPE: snippets
EXAMPLE_SELECTOR:
  NUM_EXAMPLES: 0
MODEL:
  NAME: qwen3:0.6b
  TEMPERATURE: 1.0
PROMPT:
  NAME: teacher_cfe_snippet_level_nocontext
STRUCTURED_OUTPUTTER:
  NAME: teacher_bool_nocontext
